#Install dependencies and build the application
FROM node:18-alpine AS builder

WORKDIR /app

COPY package*.json ./

# Install dependencies
RUN npm install --quiet --no-optional --no-fund --loglevel=error
RUN npm install @css-inline/css-inline-linux-x64-musl

COPY . .

RUN npm run build

#Create the final image
FROM node:18-alpine
WORKDIR /app

# Copy only the necessary files from the builder stage
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/public ./public

RUN npm install --quiet --only=production --no-optional --no-fund --loglevel=error
RUN npm install @css-inline/css-inline-linux-x64-musl

EXPOSE 8000

CMD ["npm", "run", "start:prod"]